--liquibase formatted sql

--changeset ZDAN:INSERT DATA

INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (113, 'Afghanistan', '93', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (180, 'Åland', '35818', 5);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (181, 'Åland', '35818', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (182, 'Åland', '358457', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (249, 'Albania', '355', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (97, 'Algeria', '213', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (118, 'American Samoa', '1684', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (53, 'Andorra', '376', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (147, 'Angola', '244', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (171, 'Anguilla', '1264', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (99, 'Antigua and Barbuda', '1268', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (21, 'Argentina', '54', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (92, 'Armenia', '374', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (226, 'Nagorno-Karabakh', '37447', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (42, 'Aruba', '297', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (191, 'Ascension Island', '247', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (77, 'Australia', '61', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (3, 'Australian Antarctic Territory', '6721', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (231, 'Austria', '43', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (232, 'Austria', '43', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (69, 'Azerbaijan', '994', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (11, 'Bahamas', '1242', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (26, 'Bahrain', '973', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (278, 'Bangladesh', '880', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (279, 'Barbados', '1246', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (246, 'Belarus', '375', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (176, 'Belgium', '32', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (24, 'Belize', '501', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (143, 'Benin', '229', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (144, 'Benin', '229', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (145, 'Benin', '229', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (146, 'Benin', '229', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (183, 'Bermuda', '1441', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (130, 'Bhutan', '975', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (261, 'Bolivia', '591', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (78, 'Bonaire', '599', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (275, 'Bosnia and Herzegovina', '387', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (282, 'Botswana', '267', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (95, 'Brazil', '55', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (137, 'British Indian Ocean Territory', '246', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (135, 'British Virgin Islands', '1284', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (65, 'Brunei', '673', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (57, 'Bulgaria', '359', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (58, 'Bulgaria', '359', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (223, 'Burkina Faso', '226', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (114, 'Burundi', '257', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (2, 'Cambodia', '855', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (83, 'Cameroon', '237', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (173, 'Canada', '1', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (264, 'Cape Verde', '238', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (155, 'Cayman Islands', '1345', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (184, 'Central African Republic', '236', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (198, 'Chad', '235', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (165, 'Chile', '56', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (123, 'China', '86', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (124, 'China', '86', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (125, 'China', '86', 13);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (119, 'Christmas Island', '6189164', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (51, 'Cocos (Keeling) Islands', '6189162', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (100, 'Colombia', '57', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (30, 'Comoros', '269', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (27, 'Congo', '242', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (300, 'Democratic Republic of Congo', '243', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (212, 'Cook Islands', '682', 5);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (206, 'Costa Rica', '506', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (211, 'Croatia', '385', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (70, 'Cuba', '53', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (169, 'Curaçao', '599', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (85, 'Cyprus', '357', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (71, 'Czech Republic', '420', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (284, 'Denmark', '45', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (197, 'Diego Garcia', '246', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (299, 'Chagos Islands', '246', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (66, 'Djibouti', '253', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (139, 'Dominica', '1767', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (285, 'Dominican Republic', '1809', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (293, 'Dominican Republic', '1829', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (294, 'Dominican Republic', '1849', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (149, 'East Timor', '670', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (190, 'Easter Island', '56', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (101, 'Ecuador', '593', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (102, 'Ecuador', '593', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (258, 'Egypt', '20', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (236, 'El Salvador', '503', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (204, 'Equatorial Guinea', '240', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (40, 'Eritrea', '291', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (227, 'Estonia', '372', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (228, 'Estonia', '372', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (105, 'Eswatini', '268', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (256, 'Ethiopia', '251', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (22, 'Falkland Islands', '500', 5);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (31, 'Faroe Islands', '298', 5);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (192, 'Fiji', '679', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (32, 'Finland', '358', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (33, 'Finland', '358', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (34, 'Finland', '358', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (35, 'Finland', '358', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (271, 'France', '33', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (116, 'French Guiana', '594', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (117, 'French Guiana', '594', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (64, 'French Polynesia', '689', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (93, 'Gabon', '241', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (267, 'Gambia', '220', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (37, 'Georgia', '995', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (188, 'Germany', '49', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (189, 'Germany', '49', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (170, 'Ghana', '233', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (84, 'Gibraltar', '350', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (156, 'Greece', '30', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (291, 'Greenland', '299', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (153, 'Grenada', '1473', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (17, 'Guadeloupe', '590', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (18, 'Guadeloupe', '590', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (238, 'Guam', '1671', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (162, 'Guatemala', '502', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (195, 'Guinea', '224', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (28, 'Guinea-Bissau', '245', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (163, 'Guyana', '592', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (112, 'Haiti', '509', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (106, 'Honduras', '504', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (194, 'Hong Kong', '852', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (241, 'Hungary', '36', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (89, 'Iceland', '354', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (172, 'India', '91', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (140, 'Indonesia', '62', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (141, 'Indonesia', '62', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (142, 'Indonesia', '62', 11);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (159, 'Iran', '98', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (160, 'Iran', '98', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (164, 'Iraq', '964', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (268, 'Ireland', '353', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (75, 'Israel', '972', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (107, 'Italy', '39', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (108, 'Italy', '39', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (109, 'Italy', '39', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (110, 'Italy', '39', 13);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (44, 'Ivory Coast', '225', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (185, 'Jamaica', '1876', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (199, 'Jan Mayen', '4779', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (245, 'Japan', '81', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (59, 'Jordan', '962', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (6, 'Kazakhstan', '7', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (7, 'Kazakhstan', '7', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (63, 'Kenya', '254', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (205, 'Kiribati', '686', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (266, 'Kosovo', '383', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (209, 'Kuwait', '965', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (129, 'Kyrgyzstan', '996', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (20, 'Laos', '856', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (157, 'Latvia', '371', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (67, 'Lebanon', '961', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (68, 'Lebanon', '961', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (239, 'Lesotho', '266', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (220, 'Liberia', '231', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (221, 'Liberia', '231', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (45, 'Libya', '218', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (54, 'Liechtenstein', '423', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (272, 'Lithuania', '370', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (94, 'Luxembourg', '352', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (259, 'Macau', '853', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (43, 'Madagascar', '261', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (52, 'Malawi', '265', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (87, 'Malaysia', '60', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (88, 'Malaysia', '60', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (174, 'Maldives', '960', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (14, 'Mali', '223', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (15, 'Mali', '223', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (262, 'Malta', '356', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (16, 'Marshall Islands', '692', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (126, 'Martinique', '596', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (127, 'Martinique', '596', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (72, 'Mauritania', '222', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (247, 'Mauritius', '230', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (74, 'Mayotte', '639', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (286, 'Mexico', '52', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (289, 'Federated States of Micronesia', '691', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (103, 'Moldova', '373', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (237, 'Monaco', '377', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (158, 'Mongolia', '976', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (138, 'Montenegro', '382', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (13, 'Montserrat', '1664', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (161, 'Morocco', '212', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (302, 'Sahrawi Arab Democratic Republic', '212', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (235, 'Mozambique', '258', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (80, 'Myanmar', '95', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (81, 'Myanmar', '95', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (82, 'Myanmar', '95', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (29, 'Namibia', '264', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (111, 'Nauru', '674', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (166, 'Nepal', '977', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (122, 'Netherlands', '31', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (152, 'New Caledonia', '687', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (251, 'New Zealand', '64', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (252, 'New Zealand', '64', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (253, 'New Zealand', '64', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (254, 'New Zealand', '64', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (280, 'Nicaragua', '505', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (276, 'Niger', '227', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (210, 'Nigeria', '234', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (230, 'Niue', '683', 4);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (250, 'Norfolk Island', '67238', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (154, 'North Korea', '850', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (36, 'North Macedonia', '389', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (4, 'Northern Cyprus', '90392', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (5, 'Northern Cyprus', '90392', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (86, 'Northern Mariana Islands', '1670', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (281, 'Norway', '47', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (90, 'Oman', '968', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (91, 'Oman', '968', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (265, 'Pakistan', '92', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (224, 'Palau', '680', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (218, 'Palestine', '970', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (19, 'Panama', '507', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (1, 'Papua New Guinea', '675', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (8, 'Paraguay', '595', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (186, 'Peru', '51', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (133, 'Philippines', '63', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (202, 'Pitcairn Islands', '64', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (55, 'Poland', '48', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (151, 'Portugal', '351', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (41, 'Puerto Rico', '1939', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (296, 'Puerto Rico', '1787', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (269, 'Qatar', '974', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (242, 'Réunion', '262', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (243, 'Réunion', '262', 12);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (301, 'Mayotte', '262', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (131, 'Romania', '40', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (121, 'Russia', '7', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (257, 'Abkhazia', '7840', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (277, 'Rwanda', '250', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (150, 'Saba', '599', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (225, 'Saint Barthélemy', '590', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (292, 'Saint Helena', '290', 4);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (303, 'Tristan da Cunha', '290', 4);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (38, 'Saint Kitts and Nevis', '1869', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (73, 'Saint Lucia', '1758', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (46, 'Saint Martin', '590', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (128, 'Saint Pierre and Miquelon', '508', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (283, 'Saint Vincent and the Grenadines', '1784', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (217, 'Samoa', '685', 5);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (76, 'San Marino', '378', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (208, 'São Tomé and Príncipe', '239', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (263, 'Saudi Arabia', '966', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (255, 'Senegal', '221', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (273, 'Serbia', '381', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (274, 'Serbia', '381', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (23, 'Seychelles', '248', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (260, 'Sierra Leone', '232', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (115, 'Singapore', '65', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (248, 'Sint Eustatius', '599', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (297, 'Sint Maarten', '1721', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (270, 'Slovakia', '421', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (98, 'Slovenia', '386', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (12, 'Solomon Islands', '677', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (200, 'Somalia', '252', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (201, 'Somalia', '252', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (178, 'South Africa', '27', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (47, 'South Georgia and the South Sandwich Islands', '500', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (233, 'South Korea', '82', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (234, 'South Korea', '82', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (9, 'South Ossetia', '99534', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (288, 'South Ossetia', '79298', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (244, 'South Sudan', '211', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (219, 'Spain', '34', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (213, 'Sri Lanka', '94', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (148, 'Sudan', '249', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (290, 'Suriname', '597', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (56, 'Spitzbergen', '4779', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (48, 'Sweden', '46', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (49, 'Sweden', '46', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (50, 'Sweden', '46', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (216, 'Switzerland', '41', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (10, 'Syria', '963', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (177, 'Taiwan', '886', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (79, 'Tajikistan', '992', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (167, 'Tanzania', '255', 6);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (203, 'Thailand', '66', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (132, 'Togo', '228', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (193, 'Tokelau', '690', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (240, 'Tonga', '676', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (179, 'Trinidad and Tobago', '1868', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (60, 'Tunisia', '216', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (175, 'Turkey', '90', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (187, 'Turkmenistan', '993', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (96, 'Turks and Caicos Islands', '1649', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (61, 'Tuvalu', '688', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (287, 'Uganda', '256', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (168, 'Ukraine', '380', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (62, 'United Arab Emirates', '971', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (215, 'United Kingdom', '44', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (304, 'England', '44', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (305, 'Scotland', '44', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (306, 'Wales', '44', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (307, 'Guernsey', '441481', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (308, 'Jersey', '441534', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (309, 'Isle of Man', '441624', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (310, 'Northern Ireland', '4428', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (196, 'United States', '1', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (298, 'United States Virgin Islands', '1340', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (214, 'Uruguay', '598', 8);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (134, 'Uzbekistan', '998', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (104, 'Vanuatu', '678', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (120, 'Vatican City', '3906698', 10);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (222, 'Venezuela', '58', 7);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (207, 'Vietnam', '84', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (229, 'Wallis and Futuna', '681', null);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (39, 'Yemen', '967', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (25, 'Zambia', '260', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (136, 'Zimbabwe', '263', 9);
INSERT INTO COUNTRIES (ID, NAME, CALLING_CODE, NSN_LENGTH)
VALUES (295, 'Hawaii', '1808', 10);

--rollback DELETE FROM COUNTRIES
